name: edu_assist_dynamic
description: AI-Powered Educational Management Platform - Dynamic Configuration System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation & Routing
  go_router: ^12.0.0
  
  # HTTP & API
  http: ^1.1.0
  
  # Utilities
  intl: ^0.18.1
  file_picker: ^6.1.1
  
  # State Management
  flutter_riverpod: ^2.4.9
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2

  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/fonts/

  # Fonts
  fonts:
    - family: BauhausStd-Medium
      fonts:
        - asset: assets/fonts/BauhausStd-Medium.ttf
          weight: 400

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
