name: edu_assist_dynamic
description: AI-Powered Educational Management Platform - Dynamic Configuration System
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.0.0
  http: ^1.1.0
  intl: ^0.18.1
  file_picker: ^6.1.1
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
